insert into Restaurante(nome,tipo_cozinha_id,cnpj,endereco,cep,descricao,logo,slug)values('Lahmajun - Delícias Turcas',1,'26.657.954/0001-65','Rua Doutor Penaforte Mendes, 171 - Bela Vista - Sao Paulo - SP','01308-010','Restaurante de comidas típicas turcas e árabes, como lahmajun (pizza turca), pidé (esfiha gigante de 35cm), kebabs, esfiha e kibe. Pratos/lanches veganos (como falafel), vegetarianas, fazem parte dessa pequena rede de restaurante fast-food turco com três unidades.','assets/img/restaurants/acaraje.jpeg','lahmajun');
insert into Restaurante(nome,tipo_cozinha_id,cnpj,endereco,cep,descricao,logo,slug)values('Almanara',1,'60.909.215/0001-51','R Basilio da Gama, 70 - Republica - Sao Paulo - SP','01046-020','Quando se estabeleceu na cidade, em 1950, a culinária árabe ainda não fazia parte do dia a dia paulistano, ou das grandes metrópoles brasileiras, que nem hoje em dia. Com receitas originais da família fundadora, trazidas do Líbano, e uma deliciosa cozinha artesanal, a marca preserva a riqueza de sabores de uma culinária legítima e irresistível. No cardápio, opções como falafel e frango com arroz e amêndoas. No nosso cardápio você encontra as melhores esfihas, kibes e opções árabes de São Paulo','assets/img/restaurants/almanara.jpeg','almanara');
insert into Restaurante(nome,tipo_cozinha_id,cnpj,endereco,cep,descricao,logo,slug)values('Saj',1,'22.665.513/0001-54','Rua Carneiro da Cunha, 425 - Vila da Saude - Sao Paulo - SP','41440-000','O Saj Restaurante, premiado e indicado por três anos consecutivos pela Veja SP, é conhecido por seus deliciosos pães e esfihas, bem como por seus pratos tradicionais e bem elaborados.','assets/img/restaurants/say.jpeg','saj');
insert into Restaurante(nome,tipo_cozinha_id,cnpj,endereco,cep,descricao,logo,slug)values('Salvô!',2,'37.883.007/0001-09','Rua da Glória, 654 - Liberdade - Sao Paulo - SP','01510-001','Vendemos mamitas congeladas de pratos típicos baianos.','assets/img/restaurants/salvo.jpeg','salvo');
insert into Restaurante(nome,tipo_cozinha_id,cnpj,endereco,cep,descricao,logo,slug)values('Acarajé da Rosy',2,'33.732.757/0001-29','Alameda Rio Claro, 388 - Bela Vista - Sao Paulo - SP','01332-010','','assets/img/restaurants/acaraje.jpeg','acaraje-da-rosy');
insert into Restaurante(nome,tipo_cozinha_id,cnpj,endereco,cep,descricao,logo,slug)values('China in Box - Aclimação',3,'10.685.792/0001-39','Av. Aclimação, 279 - Aclimacao - Sao Paulo - SP','01531-001','China in Box o maior delivery de comida chinesa entrega pratos feitos na hora do seu pedido, na caixinha mais conhecida do Brasil. Pratos tradicionais como yakissoba, frango xadrez, rolinho primavera e banana caramelada para pedir on-line. Peça agora!','assets/img/restaurants/china-box.jpeg','china-in-box');
insert into Restaurante(nome,tipo_cozinha_id,cnpj,endereco,cep,descricao,logo,slug)values('Ásia Express',3,'24.543.444/0001-31','Avenida Interlagos, 1435 - Jardim Umuarama - Sao Paulo - SP','04661-100','TRADIÇÃO E QUALIDADE A MAIS DE 20 ANOS EM CHINÊS E JAPONÊS! ','assets/img/restaurants/chinakim.jpeg','asia-express');
insert into Restaurante(nome,tipo_cozinha_id,cnpj,endereco,cep,descricao,logo,slug)values('Chinakim',3,'74.641.085/0001-23','Rua Humberto I, 94 - Vila Mariana - Sao Paulo - SP','04018-030','Sejam bem-vindos! Desde 2006, o Chinakim oferece o melhor da culinária chinesa. Pratos feitos com ingredientes frescos e selecionados. Crescemos pelo marketing boca a boca. E graças aos nossos clientes, completamos 15 anos. Você que não conhece, nos dê a oportunidade e experimente o nosso cardápio.','assets/img/restaurants/chinakim.jpeg','chinakim');
insert into Restaurante(nome,tipo_cozinha_id,cnpj,endereco,cep,descricao,logo,slug)values('Jardim de Napoli',4,'61.246.005/0001-93','Rua Martinico Prado, 463 - Vila Buarque - Sao Paulo - SP','01224-011','A casa do verdadeiro Polpettone!!!','assets/img/restaurants/jardim-de-napoli.jpeg','jardim-de-napoli');
insert into Restaurante(nome,tipo_cozinha_id,cnpj,endereco,cep,descricao,logo,slug)values('Osteria Generale - Bela Vista',4,'07.308.699/0001-09','Rua Doutor Fausto Ferraz, 163 - Bela Vista - Sao Paulo - SP','1333030','Cozinha italiana especializada em massas, carnes e frutos do mar.','assets/img/restaurants/osterie-generale.jpeg','osteria-generale');
insert into Restaurante(nome,tipo_cozinha_id,cnpj,endereco,cep,descricao,logo,slug)values('Lellis Trattoria',4,'43.386.903/0001-65','Al Campinas, 1615 - Jardim Paulista - Sao Paulo - SP','01404-003','No cardápio, deliciosas opções com sotaque italiano, que vão das carnes aos pescados, passando por assados, aves, massas e molhos especiais. Vale dizer: tudo é preparado com ingredientes da melhor qualidade. Entre as atrações, gnocchi de mandioquinha recheado com catupiry e manjericão, e o capeletti verdi. Opções de molho: 4 formaggi, à moda da casa, à romanesca, ao sugo, entre muitos outros.','assets/img/restaurants/lellis.jpeg','lellis-trattoria');
insert into Restaurante(nome,tipo_cozinha_id,cnpj,endereco,cep,descricao,logo,slug)values('Famiglia Mancini',4,'06.059.225/0001-08','Rua Martins Fontes, 317 - Consolacao - Sao Paulo - SP','01306-001','','assets/img/restaurants/famiglia-mancini.jpeg','famiglia-mancini');

